Implement Pl3xMap Hook.
mbax/VanishNoPacket pull request #692
Opened 2021-06-06 14:20 UTC by AAigars

This pull request implements a Pl3xMap hook that allows VanishNoPacket to hide the player on the map whenever they vanish.

2021-06-06 22:23 UTC, mbax requested changes

2021-06-06 22:23 UTC, mbax commented on pom.xml
> +    <version>3.23-SNAPSHOT</version>
Why bump when 3.22 hasn't come out yet?

2021-06-06 22:23 UTC, mbax commented on src/main/java/org/kitteh/vanish/VanishPlugin.java
> +        if(this.getConfig().getBoolean("hooks.pl3xmap", false)) {
Missing space after `if`

2021-06-06 22:23 UTC, mbax commented on src/main/java/org/kitteh/vanish/hooks/HookManager.java
> +import org.kitteh.vanish.hooks.plugins.*;
No thanks.

2021-06-06 22:23 UTC, mbax commented on src/main/java/org/kitteh/vanish/hooks/plugins/Pl3xMapHook.java
> +        if(this.enabled && this.pl3xMap != null) {
Space!

2021-06-06 22:23 UTC, mbax commented on src/main/java/org/kitteh/vanish/hooks/plugins/Pl3xMapHook.java
> +        if(this.enabled && this.pl3xMap != null) {
![image](https://user-images.githubusercontent.com/181668/120942019-0994d200-c6f4-11eb-8a2c-4c82b32c2885.png)

2021-06-06 22:39 UTC, AAigars commented on pom.xml
> +    <version>3.23-SNAPSHOT</version>
Not entirely sure, why I did bump it but it has been reverted :)

2022-02-12 22:14 UTC, mbax commented
#704

2022-02-12 22:14 UTC, closed without merging