Double-Sneak changes gamemode while in vanish
mbax/VanishNoPacket pull request #706
Opened 2022-01-17 17:53 UTC by AlessioGr

Video of it: https://www.youtube.com/watch?v=y6X1FVgFeMw

This is configurable in the `double-sneak-during-vanish-toggles-gamemode` config setting.

2022-01-17 17:57 UTC, underscore11code commented
In my opinion this should default to false - `F3` + `n` exists already to switch gamemode between gmc and gmsp, plus this is a fairly intrusive modification to a keybind.

2022-01-17 18:00 UTC, AlessioGr commented
@underscore11code Done! It defaults to false now.

2022-01-17 18:02 UTC, underscore11code approved these changes

2022-01-17 18:12 UTC, mbax reviewed
Several comments made, but here's a general one:

Calling this "toggle gamemode" is strange when it really just switches you from *whatever you were* to spectator, and then doesn't switch back but rather gives you creative. This feels 100% targeted at a specific server rather than targeted at general users.

Plus, if you're going to switch to spectator, that isn't even a vanish plugin thing anymore you're just creating a system for being a spectator. Wat.

2022-01-17 18:12 UTC, mbax commented on src/main/java/org/kitteh/vanish/VanishPlugin.java
> +        if(Settings.isDoubleSneakDuringVanishTogglesGamemode()){
Missing spaces.

2022-01-17 18:12 UTC, mbax commented on src/main/java/org/kitteh/vanish/listeners/ListenPlayerSneak.java
> +        if(event.isSneaking()){
Piles of missing spaces throughout.

2022-01-17 18:12 UTC, mbax commented on src/main/java/org/kitteh/vanish/listeners/ListenPlayerSneak.java
> +        playersAndLastTimeSneaked = new HashMap<>();
Missing `this`

2022-01-17 18:34 UTC, AlessioGr commented
> Several comments made, but here's a general one:
> 
> Calling this "toggle gamemode" is strange when it really just switches you from _whatever you were_ to spectator, and then doesn't switch back but rather gives you creative. This feels 100% targeted at a specific server rather than targeted at general users.
> 
> Plus, if you're going to switch to spectator, that isn't even a vanish plugin thing anymore you're just creating a system for being a spectator. Wat.

Everything should be fine now. It now also remembers your game mode.

This kind of functionality is enabled by default in the plugin "PremiumVanish". As I switched to vanishnopacket, I really miss this functionality.
It's pretty useful in a vanish plugin. Say you are vanish next to a player, trying to stalk them. And that player then walks into a house and closes the door. How do you get in that house?
With this double-shift functionality, I can just quickly double-shift, fly through that wall and then double-shift back to my last game-mode. It's incredibly useful if you have used it for a while.

Since it's toggled off by default now anyways, it definitely wouldn't hurt anyone.

2022-02-13 01:39 UTC, mbax requested changes
Also while you're at it could you rebase to latest? :D

2022-02-13 01:39 UTC, mbax commented on src/main/java/org/kitteh/vanish/listeners/ListenPlayerSneak.java
> +        this.playersAndLastTimeSneaked = new HashMap<>();
For persistence, let's use the PDC to avoid issues.

2022-02-14 16:17 UTC, AlessioGr commented on src/main/java/org/kitteh/vanish/listeners/ListenPlayerSneak.java
> +                    if (System.currentTimeMillis() - lastTime < 500) {
Done!

2022-02-14 16:19 UTC, AlessioGr commented on src/main/java/org/kitteh/vanish/listeners/ListenPlayerSneak.java
> +        this.playersAndLastTimeSneaked = new HashMap<>();
> For persistence, let's use the PDC to avoid issues.

For the gamemode or the last time sneaked hashmap? And I'm unsure about that, why exactly should a PDC be used there? Is this really something which needs to be persistent?

2022-02-14 16:19 UTC, AlessioGr commented
> Also while you're at it could you rebase to latest? :D

I rebased it!

2022-02-15 12:02 UTC, AlessioGr commented
I added the persistentdatacontainer - it should be ready now

2022-02-16 03:25 UTC, mbax commented
https://github.com/mbax/VanishNoPacket/commit/18a39ee5b8e3980bd2b1ba19d1a867b20f69850f

2022-02-16 03:25 UTC, closed without merging