Fix gamemode change on shift
mbax/VanishNoPacket pull request #707
Opened 2022-02-18 17:51 UTC by AlessioGr

2022-02-18 19:12 UTC, TheMolkaPL requested changes

2022-02-18 19:12 UTC, TheMolkaPL commented on src/main/java/org/kitteh/vanish/listeners/ListenPlayerOther.java
> +        }else{
style

2022-02-24 18:07 UTC, Dinty1 approved these changes

2022-02-24 21:15 UTC, mbax commented
Resolved a little differently <3

2022-02-24 21:15 UTC, closed without merging